environment:
  galleryapi:
    secure: PUx8yUU/itCarqcVAN+dxD9n0UnG9OqGawirsOfrEDj0B3TRcLSH27XWKTD/5pfG

image: Visual Studio 2017

skip_commits:
  files:
    - readme.*

only_commits:
  message: /!publish/

build: "off"

test_script:
  - ps: . .\build.ps1 -task Pester

after_test:
  - ps: . .\build.ps1 -task Clean